### ISSUE TITLE
implement PreparedStatement#bind_timestamp

### ISSUE THREAD

**Issue by suketa** [suketa/ruby-duckdb#251]
implement PreparedStatement#bind_timestamp by using PreaparedStatement#_bind_timestamp

```ruby
class Foo
  def to_str
    '2021-12-11 07:42:17.345'
  end
end
require 'duckdb'
db = DuckDB::Database.open
con = db.connect
con.query('CREATE TABLE timestamps (value TIMESTAMP)')
...
stmt = DuckDB::PreparedStatement.new(con, 'SELECT * FROM dates WHERE time_value = $1')

stmt.bind_time(Time.now)
stmt.bind_time('2021-12-11 07:42:17.285')
stmt.bind_time(Foo.new)

```

**Comment by Ashvith** [comment]
Looks like I could try out this issue too.

**Comment by Ashvith** [comment]
@suketa should I use Time and Date both for Timestamp?

**Comment by suketa** [comment]
@Ashvith 
I'm not sure which is usefull. Do you think only acceptiing `Time` object is more useful?

**Comment by Ashvith** [comment]
If we take Date as an input, then the "time" in timestamp would be **00:00:00.000000**,which would defeat the purpose of a timestamp. But I am worried about the compatibility part. What if someone created a Date object, and wants to insert it?

But I think using `Time` itself would be better, because it has all the required parameters for a timestamp.

**Comment by suketa** [comment]
@Ashvith OK, using `Time` at first.
